command:
    resource: "@CommandBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@ApiBundle/Controller/"
    type:     annotation

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


 #FOS UserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_reset:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change-password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#FOS OAuth Server Token
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user_profile_show:
    path: /

