<?php

namespace EntityBundle\Repository;

/**
 * FincaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FincaRepository extends \Doctrine\ORM\EntityRepository
{
}
