<?php

namespace EntityBundle\Repository;

/**
 * FincaRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FincaRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
