<?php

namespace EntityBundle\Repository;

/**
 * ParcelRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
