<?php

namespace EntityBundle\Repository;

/**
 * PruebadeBoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebadeBoolRepository extends \Doctrine\ORM\EntityRepository
{
}
