<?php

namespace EntityBundle\Repository;

/**
 * UserFincaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFincaRepository extends \Doctrine\ORM\EntityRepository
{
}
