<?php

namespace Proxies\__CG__\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FincaRegister extends \EntityBundle\Entity\FincaRegister implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'id', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'totalBenefits', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'sownParcel', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'collectParcel', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'collectWeight', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'registerDate', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'handsNumber', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'finca', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'salablePercent', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'deletedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'id', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'totalBenefits', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'sownParcel', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'collectParcel', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'collectWeight', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'registerDate', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'handsNumber', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'finca', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'salablePercent', '' . "\0" . 'EntityBundle\\Entity\\FincaRegister' . "\0" . 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FincaRegister $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalBenefits($totalBenefits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalBenefits', [$totalBenefits]);

        return parent::setTotalBenefits($totalBenefits);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalBenefits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalBenefits', []);

        return parent::getTotalBenefits();
    }

    /**
     * {@inheritDoc}
     */
    public function setSownParcel($sownParcel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSownParcel', [$sownParcel]);

        return parent::setSownParcel($sownParcel);
    }

    /**
     * {@inheritDoc}
     */
    public function getSownParcel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSownParcel', []);

        return parent::getSownParcel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollectParcel($collectParcel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollectParcel', [$collectParcel]);

        return parent::setCollectParcel($collectParcel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollectParcel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollectParcel', []);

        return parent::getCollectParcel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollectWeight($collectWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollectWeight', [$collectWeight]);

        return parent::setCollectWeight($collectWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollectWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollectWeight', []);

        return parent::getCollectWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegisterDate($registerDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegisterDate', [$registerDate]);

        return parent::setRegisterDate($registerDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisterDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisterDate', []);

        return parent::getRegisterDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandsNumber($handsNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandsNumber', [$handsNumber]);

        return parent::setHandsNumber($handsNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandsNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandsNumber', []);

        return parent::getHandsNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinca(\EntityBundle\Entity\Finca $finca = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinca', [$finca]);

        return parent::setFinca($finca);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinca', []);

        return parent::getFinca();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalablePercent($salablePercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalablePercent', [$salablePercent]);

        return parent::setSalablePercent($salablePercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalablePercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalablePercent', []);

        return parent::getSalablePercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

}
