<?php

namespace Proxies\__CG__\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Parcel extends \EntityBundle\Entity\Parcel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'id', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'note', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'bananaTreeNumber', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'finca', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'activity', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'name', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'location', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'deletedAt', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'parcelRegister'];
        }

        return ['__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'id', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'note', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'bananaTreeNumber', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'finca', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'activity', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'name', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'location', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'deletedAt', '' . "\0" . 'EntityBundle\\Entity\\Parcel' . "\0" . 'parcelRegister'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Parcel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinca(\EntityBundle\Entity\Finca $finca = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinca', [$finca]);

        return parent::setFinca($finca);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinca', []);

        return parent::getFinca();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivity(\EntityBundle\Entity\Activity $activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivity', [$activity]);

        return parent::addActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivity(\EntityBundle\Entity\Activity $activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivity', [$activity]);

        return parent::removeActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivity', []);

        return parent::getActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBananaTreeNumber($bananaTreeNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBananaTreeNumber', [$bananaTreeNumber]);

        return parent::setBananaTreeNumber($bananaTreeNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getBananaTreeNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBananaTreeNumber', []);

        return parent::getBananaTreeNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function addParcelRegister(\EntityBundle\Entity\ParcelRegister $parcelRegister)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParcelRegister', [$parcelRegister]);

        return parent::addParcelRegister($parcelRegister);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParcelRegister(\EntityBundle\Entity\ParcelRegister $parcelRegister)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParcelRegister', [$parcelRegister]);

        return parent::removeParcelRegister($parcelRegister);
    }

    /**
     * {@inheritDoc}
     */
    public function getParcelRegister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcelRegister', []);

        return parent::getParcelRegister();
    }

    /**
     * {@inheritDoc}
     */
    public function addNote(\EntityBundle\Entity\Note $note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNote', [$note]);

        return parent::addNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNote(\EntityBundle\Entity\Note $note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNote', [$note]);

        return parent::removeNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

}
